import { Template } from 'meteor/templating'
import '../components/insertExample/insertExample'
import '../components/autoformExample/autoformExample'
import '../components/modalExample/modalExample'
import '../components/textExample/textExample'
import '../components/selectExample/selectExample'
import '../components/multipleSelectExample/multipleSelectExample'
import '../components/autoCompleteExample/autoCompleteExample'
import '../components/arraysExample/arraysExample'
import '../components/dateTimePickerExample/dateTimePickerExample'
import '../components/DynaView'
import './index.html'
